### ISSUE TITLE
[Feature] Allow changing Module construction attributes in setup 

### ISSUE THREAD

**Issue by PhilipVinc** [google/flax#1057]
Consider the following snippet, where I have a linen Module which has two module attributes.
One of those (`dtype1`) has a default, the other one, `dtype2`, I'd like to default to `dtype1`, unless it's specified.
To achieve this, I give it a default value of None and in `setup` I change it accordingly.

However, since Flax==3.1, I believe because of #938 , this behaviour is disallowed.
As the module is effectively frozen after setup is called, why isn't this behaviour allowed? 
I believe it would suffice to eliminate the following check in `linen.module.py:514` 
```python
    if is_dataclass_attr:
      if self._state.in_setup:
        raise TypeError("Module construction attributes are frozen.")
```

This is my example usage

```python
import jax
import jax.numpy as jnp
import flax
import flax.linen as nn
from typing import Any

class Test(nn.Module):
  dtype1: Any  = jnp.float32
  dtype2: Any = None

  def setup(self):
    if self.dtype2 is None:
      self.dtype2 = self.dtype1

  @nn.compact
  def __call__(self, x):
    dense = nn.linear.Dense(name="dense", dtype=self.dtype2)
    return jnp.asarray(dense(x), dtype=self.dtype1) + 1

model = Test()
pars = model.init(jax.random.PRNGKey(0), 1)
>>> pars = model.init(jax.random.PRNGKey(0), 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/flax/linen/module.py", line 884, in init
    _, v_out = self.init_with_output(rngs, *args, method=method, **kwargs)
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/flax/linen/module.py", line 862, in init_with_output
    return self.apply(
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/flax/linen/module.py", line 841, in apply
    return apply(fn, mutable=mutable)(variables, rngs=rngs)
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/flax/core/scope.py", line 608, in wrapper
    y = fn(root, *args, **kwargs)
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/flax/linen/module.py", line 834, in <lambda>
    fn = lambda scope: method(self.clone(parent=scope), *args, **kwargs)
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/flax/linen/module.py", line 269, in wrapped_module_method
    self._try_setup()
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/flax/linen/module.py", line 661, in _try_setup
    self.setup()
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/flax/linen/module.py", line 277, in wrapped_module_method
    y = fun(self, *args, **kwargs)
  File "<stdin>", line 5, in setup
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/flax/linen/module.py", line 513, in __setattr__
    raise TypeError("Module construction attributes are frozen.")
TypeError: Module construction attributes are frozen.```

**Comment by jheek** [comment]
Keeping Modules frozen guarantees some important invariants that we need for the Module abstraction to work correctly (especially when interacting with JAX transforms):

1. Cloning, we clone Modules based on their attributes and by allowing mutations on the attribute we cannot guarantee that a clone behaves the same (we also want to avoid deep cloning trickery).
2. setup is called lazily so accessing the attribute from outside can lead to surprising results where the lazy init hasn't happened yet.

**Comment by avital** [comment]
More concretely, I believe the following should work:

```py
class Test(nn.Module):
  dtype1: Any  = jnp.float32
  dtype2: Any = None

  def setup(self):
    if self.dtype2 is None:
      self.final_dtype = self.dtype1
    else:
      self.final_dtype = self.dtype2

  @nn.compact
  def __call__(self, x):
    dense = nn.linear.Dense(name="dense", dtype=self.final_dtype)
    return jnp.asarray(dense(x), dtype=self.dtype1) + 1
```

**Comment by avital** [comment]
(You can't change attributes that are defined in the dataclass because we need those to stay constant for cloning modules, but you can define new attributes)

**Comment by PhilipVinc** [comment]
I was indeed not advocating for unfreezing modules, but from the docs it seemed to me it should be possible to change module attributes in setup...
Indeed I understand why that is not possible.

Thank you for your explanation

**Comment by PhilipVinc** [comment]
@avital , Am I allowed to use dataclass's `__post_init__` for that? that should not be called lazily?

**Comment by avital** [comment]
The limitation isn't due to a technicality, it's a fundamental limitation -- for Modules to be directly convertible into pure functions and for them to interoperable with JAX transformations, it must be possible to clone any module instance by looking at its attributes alone, and creating a new instance from them, and be guaranteed that what you got is identical to the original.

If you modify attributes after initialization, then you're breaking that invariant, and if you use any such module with JAX transformations inside (e.g. remat for lower memory consumption), you will actually be running a *different module* than you think you are.

**Comment by avital** [comment]
Think about module attributes like a `let` directive in some programming languages (in particular many functional programming languages) -- you can assign the variable a value only once.

**Comment by llCurious** [comment]
Hey, @avital. The discussion above is of great value to me. I have a use case that requires to modify the model construction after setup. Do you have any suggestions or workaround so that the goal can be achieved? A code snippet is as follows:

``` Python
class Example(nn.Module):
  dtype: Any = jnp.float32

  def setup(self):
    self.l1 = nn.Dense(5, dtype=self.dtype)
    self.l2 = nn.LayerNorm(10, dtype=self.dtype)

  def __call__(self, x):
    return jnp.asarray(self.l2(self.l1(x)))
```

The `Example` Module could be some complext models provided by the community like BERT (in pip packages). 

My purpose is to compute the l1 layer with `jnp.float16` like:
``` Python
model = Example()
model.l1.dtype=jnp.float16 # of course does not work since model.l1 is not accessable
```

Options I have are:
1. manually set the dtype. In this case, the src code should be modified and not appropriate.
2. use contextlib to hack the Dense layer implementation. That is, whatever the dtype in Example is, we use float16 for Dense.
3. Do you have any ideas? I hope to directly modify the dtype for different module/layer after setup
