### ISSUE TITLE
super().__call__ not generally safe to call in subclass __call__

### ISSUE THREAD

**Issue by levskaya** [google/flax#1192]
```
class Foo(nn.Module):
  @nn.compact
  def __call__(self, x):
    return nn.Dense(4)(x)

class Bar(Foo):
  @nn.compact
  def __call__(self, x):
    y = super().__call__(x)
    return nn.Dense(4)(y)

k = random.PRNGKey(0)
x = random.randint(k, (4, 7), 0, 256)

variables = Bar().init(k, x)
y = Bar().apply(variables, x)
```
returns 
```
AssignSubModuleError: Submodule Dense must be defined in `setup()` or in a method wrapped in `@compact` (https://flax.readthedocs.io/en/improve-error/flax.errors.html#flax.errors.AssignSubModuleError)
```

This happens because the parent `super().__call__` is wrapped to mark itself as "compact" upon entry, clearing the "compact" state upon exit, leading to any remaining variable/submodule instantiations in the subclass `__call__` causing an error because the function no longs "looks compact".

I think we could fix this by adding a bit of logic to the `wrap_method_once` function and by passing in the class to `wrap_method_once` during subclass initialization to detect when `self` isn't an instance of the class it's "supposed to be", and having the wrapper acting as a passthrough.

**Comment by avital** [comment]
(copying from an offline discussion -- if we "formally" support module inheritence and test it rigorously, i think it may be fine to disallow the base class from having optional attributes. otherwise we'd have to reorder the base class optional attributes and put them at the end -- but that would be very confusing for folks who use positional args as opposed to kwargs)

**Comment by jheek** [comment]
An alternative fix would be to allow nested compact calls
