### ISSUE TITLE
remat: wrapper() got an unexpected keyword argument 'use_running_average'

### ISSUE THREAD

**Issue by deasmhumhna** [google/flax#1455]
### Problem you have encountered:

The transformed module returned by `remat` does not expect same keyword arguments as original when used as a submodule in `@compact` decorated `__call__` method.

### What you expected to happen:

The transformed module expects the same keyword arguments.

### Logs, error messages, etc:

```
TypeError: wrapper() got an unexpected keyword argument 'use_running_average'
```

### Steps to reproduce:
Whenever possible, please provide a *minimal example*. Please consider submitting it as a Colab link.

```
import jax
import flax.linen as linen 

from jax import numpy as jnp
from typing import Optional

class MyModule(linen.Module):
    
    @linen.compact
    def __call__(self, x, train: Optional[bool]=True):
        return linen.remat(linen.BatchNorm)()(x, use_running_average=not train)

model = MyModule()
key = jax.random.PRNGKey(0)
variables = model.init(key, jnp.ones((10,), jnp.float32))
```
https://colab.research.google.com/drive/1JsmxSn4Msor5D6G5XHpokfHOFlUcsXIJ?usp=sharing

**Comment by ZYHowell** [comment]
Same. This seems because pack [here](https://github.com/google/flax/blob/095517e679d1687b13e106354e966e418756e535/flax/core/lift.py#L73) returns function(see L83 in the same file below) does not accept keyword arguments. When I manually adds **kwargs to the parameter list of the wrapper and L177-L180, the problem is solved.

**Comment by deasmhumhna** [comment]
When I tried this in my actual code where I jit the `apply` function, I get a `ConcretizationTypeError` error, while in the minimal example it throws `IndexError: list assignment index out of range`.

**Comment by ZYHowell** [comment]
I can reproduce the problem. Now the problem seems from jit+remat, since when I remove all my modification and turns kwargs into args like [this](https://gist.github.com/ZYHowell/b441e209717fbd715b46d4ca5c572a5a), there is still a likewise problem. But leaving either alone can work well. I also tried `nn.jit`, but still no progress.

**Comment by deasmhumhna** [comment]
I'll try looking through the error stack trace and associated functions more thoroughly soon. Maybe somewhere in the wrapping function the `args` and `kwargs` unintentionally get converted into jax arrays? I wonder if the behavior is reproduced with a type like `str` that cannot be forced into a jax object?
