### ISSUE TITLE
Documentation - Struct initializing with __post__init not possible

### ISSUE THREAD

**Issue by GJBoth** [google/flax#1628]
Hi,

I'm trying to create a dataclass with an initialization method, a la 
```
@struct.dataclass
class LightField:
    u: jnp.ndarray = struct.field(init=False)
    k: jnp.ndarray
    init_fn: Callable = struct.field(pytree_node=False)
    
    def __post_init__(self):
        self.u = self.init_fn(self.k)
```

`__post_init__` is called, but I can't update `u` because the dataclass is immutable, as it's defined as frozen dataclass. This is not strictly a flax issue, but it took me a while to figure this out. An (ugly) workaround is to use:

```
 def __post_init__(self):
    super().__setattr__('u', self.init_fn(self.k, self.z, self.lambda_))

```
However, in this case we can't `vmap` the initialization. It might be beneficial to make a note of this in the documentation or implement a workaround?

**Comment by jheek** [comment]
I don't think this will work as you expect because __post_init__ will be called every time this dataclass is tree_mapped (e.g.: when passing it to a JAX functions like vmap). What makes dataclasses easy to use in combination with pytrees is that they are vanilla data structures so basically they are immutable and constructor args == instance fields.

Personally I generally prefer explicit smart constructors as static/class methods so in your case:
```
@struct.dataclass
class LightField:
    u: jnp.ndarray
    k: jnp.ndarray
    
    def create_from_k(self, k, init_fn):
       return LightField(u=init_fn(k), k)
```
