### ISSUE TITLE
`nn.compact` and `setup` giving different results

### ISSUE THREAD

**Issue by franchesoni** [google/flax#1767]
### Problem you have encountered:
I am trying to understand the behavior of `nn.compact` and `setup`. They give different results. + the documentation and source code are not very clear: where should I use `make_rng`? what's the difference between the approaches?

### What you expected to happen:
Give the same results

### Logs, error messages, etc:
None

### Steps to reproduce:
https://colab.research.google.com/drive/1dkk8ynk9g61RKLJbcoV6QpY98FSAFONh?usp=sharing

**Comment by marcvanzee** [comment]
You should make sure the names of your submodules are the same, because Flax generates RNGs for submodules by folding in the module name. In your case when you use `setup` the names of the submodules are equal to the names to assign to `self` (`dropout1` and `dropout2), while when you use compact they are auto-generated and something like `Dropout_0`, `Dropout_1`. If you explicitly set those to `dropout1` and `dropout2` using the `name=` kwargs, the results should be the same.

Let me know if this resolved your issue!

**Comment by marcvanzee** [comment]
Closing this, feel free to re-open if I misunderstood something.
