### ISSUE TITLE
Example: pix2pix

### ISSUE THREAD

**Issue by us** [google/flax#193]
I want to add pix2pix example. We can discuss any question, issue, etc. on here. I already have some work about pix2pix as a draft pr.

Related issue: #192 
Related pr: #186

**Comment by marcvanzee** [comment]
Hi us, thanks a lot for creating this issue so we can discuss your example!

We currently haven't properly documented our examples policy (we will be doing this in the coming weeks), so apologies for that. However, our policy is more or less that the flax repository should contain a few examples of using flax in different domains of ML, without become too biased towards a specific domain (e.g., vision or nlp). In this way, we aim to show the flexibility and usefulness of flax, without getting too much into domain-specific details. If someone implements an architecture that is more involved, then we recommend they put it in a separate repository and we will happily link to it from our examples page. (Although our examples currently aren't in this state exactly yet, we will be fleshing this out more soon.)

Now coming to your example, I think we would probably prefer to first have a base GAN implementation before we get into more specific architectures. However, I think it is great you implemented this, so what do you think about adding this example to a separate repository, so that we can link to it from our "examples" page?

Hope that makes sense, and let me know if you have any questions!

**Comment by us** [comment]
Hi @marcvanzee ,
Thank you for replying.
I understand your thought. I would like to add a separate repository. I had to stop working because of school exams but as soon as I finish I will continue to work on this project. 
I'll write my questions here.

**Comment by avital** [comment]
Hi @us, I want to close this issue so that we can keep GitHub issues for real open tickets. We should consider making a proper forum for Flax. For now I'll close this issue but feel free to comment more on it if you have more questions.
