### ISSUE TITLE
`typing.get_type_hints()` is broken for linen modules

### ISSUE THREAD

**Issue by brentyi** [google/flax#1947]
I have some serialization code that involves a recursive call to `get_type_hints()`, which breaks for flax modules:
```python
from typing import get_type_hints

from flax import linen as nn


class Network(nn.Module):
    layers: int

# Fails!
# NameError: name 'Module' is not defined
print(get_type_hints(Network))
```

The reason for this seems to be that forward references are (seemingly unnecessarily) used when fields are being dynamically added to the module dataclass, but the typing module tries to resolve these names in the wrong local namespace:
https://github.com/google/flax/blob/96c78cd1bb43dfacfb8a999f3155facec00ecb3b/flax/linen/module.py#L533-L534

This can be confirmed because adding one extra line fixes the error:
```python
from typing import get_type_hints

from flax import linen as nn
from flax.linen.module import Module, Scope, _Sentinel  # New


class Network(nn.Module):
    layers: int

# Works!
# {'layers': <class 'int'>, 'parent': typing.Union[typing.Type[flax.linen.module.Module], typing.Type[flax.core.scope.Scope], typing.Type[flax.linen.module._Sentinel], NoneType], 'name': <class 'str'>}
print(get_type_hints(Network))
```

**Comment by marcvanzee** [comment]
Nice catch, that forward reference is indeed unnecessary because it is only necessary when the class being defined is in the signature of the class method (see [PEP 484](https://www.python.org/dev/peps/pep-0484/#forward-references)).

I wasn't aware that this breaks `get_type_hints` though, but it seems to be a known issue. From the [typing documentation](https://docs.python.org/3/library/typing.html#typing.get_type_hints):

_"Note [get_type_hints()](https://docs.python.org/3/library/typing.html#typing.get_type_hints) does not work with imported [type aliases](https://docs.python.org/3/library/typing.html#type-aliases) that include forward references. Enabling postponed evaluation of annotations ([PEP 563](https://www.python.org/dev/peps/pep-0563)) may remove the need for most forward references"._

I'll take a look at your fix.
