### ISSUE TITLE
Create near state of the art object detection example

### ISSUE THREAD

**Issue by georgedahl** [google/flax#202]
An object detection example would be extremely useful. A very good single-stage detection model that runs on Microsoft COCO would be an extremely useful starting point for flax users who need to do detection.

The single-stage detection models get pretty good results these days and should be simpler to implement, but it would be good if someone who is familiar with the detection literature could comment on this issue and suggest something that isn't too far from the state of the art (at least as good or better than RetinaNet).

**Comment by avital** [comment]
I believe that @DanGraur has just finished implementing one -- Dan, is it open sourced yet?

**Comment by DanGraur** [comment]
It should be finished, yes. It is, however, still parked in PR #427. I think the reason for this is that I have to write a Colab script which shows the results of the inference, and I haven't managed to do this yet due to the fact that downloading the MS-COCO dataset is not viable inside the Colab VM (takes too long, and it's too big for the storage). I've received some GCP resources, so hopefully they will help with this, and with providing some final eval numbers.

Regardless, the code is still good, and can be used as a base for object detection projects. I also have some extra commits to push (they're ready and waiting) after this PR gets merged, which includes some useful operations like Non-Maximum Suppression, Top-K selection and filtering.

**Comment by avital** [comment]
@georgedahl -- I think [Scenic](https://github.com/google-research/scenic) has object detection models, have you taken a look there?

**Comment by avital** [comment]
Closing because at this point there are many good Flax models implemented outside of the official flax/examples directory, and I think Scenic is probably the best place to look for one of these.
