### ISSUE TITLE
`traverse_util.flatten_dict` function works differently in two different python environments despite same version of flax being installed

### ISSUE THREAD

**Issue by felixzli** [google/flax#2093]
Hello,

I have two python environments both with flax 0.4.0 on two different VMs. In one of the python environments, `traverse_util.flatten_dict` cannot be used with the keyword argument `sep`. In the other python environment, `traverse_util.flatten_dict` works with the keyword argument `sep`. I have posted screenshots below showing this.
<img width="495" alt="image" src="https://user-images.githubusercontent.com/31943554/165862299-4d162519-ee3f-47f1-bb99-7476cd90b61c.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/31943554/165863081-32aa40e0-fd92-4cb0-94ad-e0b30af3b002.png">

Thanks

**Comment by andsteing** [comment]
You should install `flax==0.4.1` if you want to use `flatten_dict()` with the `sep=` param, see:
https://github.com/google/flax/compare/v0.4.0...v0.4.1

Your problem is probably that you installed a version between `0.4.0` and `0.4.1` releases in the first example above.

1. This works and prints `0.4.1`

```python
!pip install -q flax==0.4.1
import flax
print(flax.__version__)
flax.traverse_util.flatten_dict({'x': 0}, sep='/');
```

2. This prints `0.4.0` and **fails**

```python
!pip install -q flax==0.4.0
import flax
print(flax.__version__)
flax.traverse_util.flatten_dict({'x': 0}, sep='/');
```

3. This prints `0.4.0` and **works**

```python
!pip install -q git+https://github.com/google/flax.git@63a286137d723666466632b9ed91902fbd092ddd
import flax
print(flax.__version__)
flax.traverse_util.flatten_dict({'x': 0}, sep='/')
```

**Comment by felixzli** [comment]
Thanks for the help
