### ISSUE TITLE
0.6.3 introduced a circular dependency with orbax

### ISSUE THREAD

**Issue by mattsoulanille** [google/flax#2707]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`:
- Python version:
- GPU/TPU model and memory:
- CUDA version (if applicable):

### Problem you have encountered:
Flax 0.6.3 added a [dependency on orbax](https://github.com/google/flax/blob/main/setup.py#L33), which [has a dependency on flax](https://github.com/google/orbax/blob/main/pyproject.toml#L28). This is causing https://github.com/tensorflow/tfjs/issues/7159 in the TensorFlow.js repository. TFJS resolves pypi packages using Bazel, which does not support circular dependencies.

Was this change intentional? If so, I can file a bug with rules_python instead, although [last time this kind of circular dependency issue arose, it was determined to be a bug in the downstream package](https://github.com/bazelbuild/rules_python/issues/439#issuecomment-810736253). I'm not sure if that true in this case, though.
### What you expected to happen:
No circular dependency.

### Steps to reproduce:
Whenever possible, please provide a *minimal example*. Please consider submitting it as a Colab link.

**Comment by mattsoulanille** [comment]
Thanks! TFJS has pinned flax to 0.6.2 for now, so we are unblocked for the moment.

**Comment by IvyZX** [comment]
In internal equivalents of Bazel, the BUILD rules are specified so that there is no actual code-level circular dependency between Flax and Orbax. Is it possible to specify BUILD rules in the open-source codebase so that Bazel knows how to run it?

**Comment by IvyZX** [comment]
Discussed with @mattsoulanille and @levskaya offline. TFJS seems to be okay with pinning `flax==0.6.2` for a while, since it seems a bit tricky to figure out a Bazel-based solution for TFJS that recognizes Flax and Orbax dependency graph at code-level.

But in the long term this circular dependency of Flax and Orbax may be a blocker for other installations as well. Generally the right direction is probably to cut Orbax's dependency on Flax, since Orbax is designated for general (JAX/TF) checkpointing.

Right now Orbax is dependent on Flax for `serialization.py` and `traverse_util.py` packages. 
**Most code can be copied to Orbax as a temporary solution**, except for the `_STATE_DICT_REGISTRY` in `serialization` which allows user to register serialization solution for customized leaf types. If Orbax copies `serialization.py` and creates its own registry, custom types registered through Flax will fail to propagate. I wonder if Flax can simply frame its `register_serialization_state()` as a wrapper of Orbax's state registration. 

Either way, gonna have more discussion with Orbax and figure out a long-term solution.

**Comment by cgarciae** [comment]
For the future, here are some ideas:
* Orbax becomes the owner of `seralization.py`, this makes sense for a check-pointing library. On the Flax side we add some wrappers.
* Create a new `flax-serialization` library which both libraries can depend on to avoid the circular dependency.

**Comment by levskaya** [comment]
We have to maintain control of traversals / flattening nested-dict, struct dataclass, etc.  As we use those for more things than just checkpoints.  One hope is to enhance JAX pytree calls with the notion of "paths" such that we could remove our hacky state-dict registry altogether - but this is still in discussion.

**Comment by aschleck** [comment]
We hit this today using a rules_python Bazel repository :(. Has there been any further thought into resolving this?

**Comment by samuela** [comment]
Just came across this today trying to upgrade flax in nixpkgs...

**Comment by cgarciae** [comment]
We just released `0.6.5` can you try again and see if its fixed for you?

**Comment by samuela** [comment]
Looking at 0.6.5 it appears that there's still a dependency on orbax: https://github.com/google/flax/blob/524629eb0083dd07c982002a36d20f9d3863b376/setup.py#L33

**Comment by wookayin** [comment]
I guess this is a problem of orbax depending on flax?

**Comment by samuela** [comment]
> I guess this is a problem of orbax depending on flax?

Or the other way around, depending how you want to think about it. All comes down to how flax/orbax maintainers choose to remedy the situation. Seems like https://github.com/google/flax/issues/2707#issuecomment-1349419277 is the latest on that.

**Comment by levskaya** [comment]
Hi all - sorry for the delay on this issue!  The underlying issue is that orbax has been using the flax serialization routines, partly for some backwards-compatibility reasons, but mainly because the simple flax "state dict" machinery was a common way to handle deriving the "key paths" to each leaf in a pytree.  The circular dependency is occurring since we're trying to transition to being able to use orbax for checkpoints.

We're trying to resolve this issue in a fundamental way by adopting a mechanism in jax itself to define the key-paths to pytree leaves so that we needn't use our relatively simple state-dict abstraction in other libraries (and ultimately to delete it ourselves).

Our sincere apologies for the build troubles with this circular dependency - we and the orbax maintainers are working to try to resolve it in the next week or so.

**Comment by wookayin** [comment]
Hi! When will this be fixed?

**Comment by daskol** [comment]
@wookayin Fix was promised soon in #2882. :smiley:

As far as I remember `pip` actually installs `flax` and `orbax` but report broken dependency resolution.

**Comment by IvyZX** [comment]
As Flax depends on `orbax-checkpoint` now, there is no longer a circular dependency.
