### ISSUE TITLE
Flax depends on Tensorflow

### ISSUE THREAD

**Issue by cgarciae** [google/flax#280]
Given Jax is independent from TF, why is there a need for it in Flax?

**Comment by mohitreddy1996** [comment]
Hi, 

TF is not used for model training but I believe we currently have usages of TF for:
- tf.data.Dataset (and transformations around it): We currently use publicly available datasets in [Tensorflow Datasets](https://www.tensorflow.org/datasets) which allows us to standardize how datasets downloaded and prepared.
- tf.io.gfile: This allows us to read/write to different types of file systems including network or cloud FS like GCS. We couldn't find a better alternate yet (We had a detailed discussion [here](https://github.com/google/flax/pull/144#discussion_r415436410), decided to stick with gFile for now) but more than happy to listen to your recommendations on this. Basic requirements:
  - Similar API to `file` object
  - local and remote (network and cloud) FS IO

Please let me know if you find cases otherwise.

**Comment by danielsuo** [comment]
Will also chip in and say that the base package does not require `tensorflow` (see [here](https://github.com/google/flax/blob/master/setup.py#L29)). However, several of the examples _do_ require `tensorflow` and its family of packages. You'll see that the tests have some TF dependencies.

In other words, `pip install flax` won't install `tensorflow` and there is no requirement that you use `flax` with `tensorflow`.

Closing for now, but please re-open if you feel we haven't properly addressed!
