### ISSUE TITLE
Bug due to inexact version dependencies in Flax

### ISSUE THREAD

**Issue by lucaslingle** [google/flax#2886]
It seems that flax's ```setup.py``` uses a loosely-specified dependency on Orbax and many other libraries. Today I encountered an error from the latest Orbax release, and wrote a separate [ticket](https://github.com/google/orbax/issues/224) for it.

I wanted to post here to ask/encourage Flax to specify exact version dependencies, so that people know they're getting fully reproducible builds/installs. It would have saved me a fair bit of trouble today. Thanks for considering :)

**Comment by IvyZX** [comment]
Thanks for raising the concern. Flax's general policy is to keep the library dependencies unpinned if possible, in order to make sure our library always work with the latest versions of our dependencies. It also gives the user freedom to install various versions of libraries.

I believe most Google libraries around JAX ecosystem (Flax, and Orbax) develops with the latest version in mind. It's generally good practice for us to roll up the minimal version of JAX as we develop on top of more recent JAX features, and the next Flax release will actually [require](https://github.com/google/flax/blob/main/setup.py#L29) JAX>=0.4.2, which will make your debugging easier. But that also means you might consider upgrading your JAX version as well! Let me know if you have any more concerns.

**Comment by lucaslingle** [comment]
Ok, thanks for explaining. I will use the latest version where possible. 

My main concern is to have a codebase that does not require refactoring in the future in order to keep working, as I am going to be open-sourcing the codebase for a conference paper. As a workaround for the unpinned versions used by Flax, I will specify versions for all of Flax's dependencies in my own project's ```setup.py```. 

Thanks!

**Comment by 8bitmp3** [comment]
@lucaslingle Make sure you ping us when the paper is out :partying_face: Maybe we can add it to community examples in https://flax.readthedocs.io/en/latest/examples.html
