### ISSUE TITLE
Difference between Flax and JAX Stax

### ISSUE THREAD

**Issue by DarrenZhang01** [google/flax#377]
Hi, excited to see this set of NN functionalities! Could anyone introduce the major differences between Flax and JAX stax? Thanks!

**Comment by 8bitmp3** [comment]
### stax, flax, and haiku - all JAX

@DarrenZhang01 my understanding is as follows:

- **stax** is an experimental mini-library built with JAX for functional neural networks. This explains why it's in [`google/jax/experimental`](https://github.com/google/jax/tree/master/jax/experimental). Note that it says: _"each mini-library is meant to be an inspiration, but not a prescription"_
- **flax**, on the other hand, is a "proper" neural network library, which has it's own repo - [`google/flax`](https://github.com/google/flax) - as well as a separate docs site - [flax.readthedocs.io](https://flax.readthedocs.io).

Then there's **[haiku](https://github.com/deepmind/dm-haiku)** that's developed by some of the engineers behind DeepMind's [Sonnet](https://github.com/deepmind/sonnet). Both Sonnet for TensorFlow and haiku for JAX help the folks at DeepMind run their experiments at _scale_ (_"Many users have found Sonnet to be a productive programming model in TensorFlow; Haiku enables the same experience in JAX"_). See this [full list of benefits](https://github.com/deepmind/dm-haiku#why-haiku). _"Haiku builds on the programming model and APIs of Sonnet, a neural network library with near universal adoption at DeepMind"_.

**Comment by levskaya** [comment]
Yeah, the major difference is that stax is a powerful but lightweight demo and builds layers by composition using combinators in 'point-free style'.  

Flax tries to provide all the tooling needed to build and train NN models on JAX, from small models all the way to large distributed training runs on thousands of devices.  It tries to follow a more pythonic style that uses variable names and assignment to specify the DAG flow of data through the network rather than relying on combinator alchemy that tends to result in "write-only" code.

**Comment by DarrenZhang01** [comment]
Thanks for the explanation, @8bitmp3  and @levskaya ! @levskaya , what does it mean by "write-only" code?

**Comment by david-waterworth** [comment]
I believe  "write-only code" is a way of saying it's hard to understand - i.e. only the person who wrote it can understand and maintain it.

**Comment by DarrenZhang01** [comment]
I see. Thanks!
