### ISSUE TITLE
How to share optimizer object between multiple processeses

### ISSUE THREAD

**Issue by sharavsambuu** [google/flax#380]
Hello, first of all thanks to you guys for making this cool library.

I wanted to implement A3C with multiprocessing and
my issue is I couldn't find the way to share optimizer object between multiple processes due to serialization.

What is the proper way to implement training with multiprocessing or share optimizer between processes?

**Comment by levskaya** [comment]
In general if you're trying to serialize complicated things in a multiprocessing setting, I'd recommend using [cloudpickle](https://github.com/cloudpipe/cloudpickle) which is much more robust than native pickling.  

However, you can always transfer the underlying data (in the case of an optimizer, the `optimizer.target`, and reconstitute the optimizer object on each MP worker from this raw, serializable data.  As to updating / sync'ing shared multiprocess data efficiently and safely: books can be written on the topic, but that's not something flax tries to manage itself (we manage device memory and SPMD primitives, but not fine-grained "multihost" parallel computations since they're extremely algorithm dependent).

**Comment by sharavsambuu** [comment]
Perfect! Thanks for the detailed answer.
