### ISSUE TITLE
Will nnx.MultiHeadAttention support flash att?

### ISSUE THREAD

**Issue by Mddct** [google/flax#4009]

**Comment by cgarciae** [comment]
Hey! There is currently no plans for supporting Flash attention in Flax (Linen or NNX).

**Comment by IvyZX** [comment]
JAX has purely functional Flash attention kernels: [TPU](https://github.com/google/jax/blob/787e7473641bbc017ada8176417573404ec7c6a1/jax/experimental/pallas/ops/tpu/flash_attention.py#L4) & [GPU](https://github.com/google/jax/blob/787e7473641bbc017ada8176417573404ec7c6a1/jax/experimental/pallas/ops/gpu/attention.py).

Since flash attention optimizes things in kernel level, you can just fork the NNX MultiHeadAttention and call the JAX kernel instead (likely substitute around the `self.attention_fn()` call part).

**Comment by Mddct** [comment]
> JAX has purely functional Flash attention kernels: [TPU](https://github.com/google/jax/blob/787e7473641bbc017ada8176417573404ec7c6a1/jax/experimental/pallas/ops/tpu/flash_attention.py#L4) & [GPU](https://github.com/google/jax/blob/787e7473641bbc017ada8176417573404ec7c6a1/jax/experimental/pallas/ops/gpu/attention.py).
> 
> Since flash attention optimizes things in kernel level, you can just fork the NNX MultiHeadAttention and call the JAX kernel instead (likely substitute around the `self.attention_fn()` call part).

great, thnks
