### ISSUE TITLE
Easier customized carry initialization for GRUcell

### ISSUE THREAD

**Issue by LysSanzMoreta** [google/flax#559]
Hi!

I am trying to initialize a GRUcell using a carry initialized using numbers sampled from the normal distribution, instead of the default initializer to 0. As seen here: https://github.com/google/flax/blob/e58dea2e55257648cee0b6485c09f3b6013b7d38/tests/linen/linen_test.py#L207

I want to do this:

`carry0 = nn.GRUCell.initialize_carry(rng, (2,), 4,init_fn= jax.nn.initializers.normal)`

and simply return an array, instead of a function, which is happening right now....

Or is there an alternative to initialize the carry to normally distributed numbers? Maybe I missed something

Thanks!

**Comment by andsteing** [comment]
Hi

Sorry for the delayed response, this question fell through the cracks in our rotation...

the `nn.initializers.normal` (i.e. without `jax`) initializer is different from e.g. `nn.initializers.zeros` because you need to specify what `stddev` you want the normal initializer to use.

The correct invocation would be

```python
nn.GRUCell.initialize_carry(rng, (2,), 4, init_fn= jax.nn.initializers.normal(stddev=1e-2))
```

Or, alternatively, if you want to go with the default:

```python
nn.GRUCell.initialize_carry(rng, (2,), 4, init_fn= jax.nn.initializers.normal())
```

**Comment by LysSanzMoreta** [comment]
Now that I see it, I apologize for this question hahah, I feel a little silly. I tried to use the jax.nn.initializers.normal() but there was some dtype error and then I think I went down a rabbit hole for no reason thinking it did not work. It's working now , thanks and so sorry.
