### ISSUE TITLE
Need to add all optimizers to Read The Docs

### ISSUE THREAD

**Issue by avital** [google/flax#661]

**Comment by 8bitmp3** [comment]
@avital I see there're only Adam and Momentum here: 
https://flax.readthedocs.io/en/latest/flax.optim.html?highlight=optimizer#optimizers
So, is this about adding more optimizers and/or documenting them? I've done the latter for another OS lib, so can reuse that material. Cheers 👋

**Comment by avital** [comment]
Yes, we need to add the other optimizers to this list and make sure they have good docstrings.

**Comment by avital** [comment]
It'd be great if you wanted to give this a shot!

**Comment by 8bitmp3** [comment]
@avital As for the former - adding optimizers - are you considering porting the common optims like RMSProp, Adagrad, etc from [`jax.experimental.optimizers`](https://jax.readthedocs.io/en/latest/_modules/jax/experimental/optimizers.html)?

**Comment by avital** [comment]
We have those, they're just not documented: https://github.com/google/flax/tree/master/flax/optim

**Comment by BertrandRdp** [comment]
Hey, actually we have a PR for this issue #672 that was missing review (only adressing RTD and some docstrings). Thanks for working on Adam!

**Comment by 8bitmp3** [comment]
That's awesome 👍 @BertrandRdp Let's have your PR reviewed first (@avital PTAL https://github.com/google/flax/pull/672) - you address more things and throw a wider net, including the addition of `autoclass` for all optims so that users can see them on the site. Then, we can add Adam-only stuff (a chunk of a docstring from https://github.com/google/flax/pull/733). I'm planning to update all optims one by one, as I've got material ready from other work.

**Comment by marcvanzee** [comment]
Slightly related: https://github.com/google/flax/pull/909

That PR doesn't change the docstrings on optimizers but does make them appear nicer on RTD, and clarifies the user of the base optimizer classes Optimizer, OptimizerDef, and MultiOptimizer.

**Comment by andsteing** [comment]
Since

https://github.com/google/flax/blob/11f8151d29fc37051d5a2221d8ec39b5b47e388f/flax/optim/__init__.py#L15-L24

I don't think we need to document these "effectively deprecated" optimizers in RTD. Closing.
