### ISSUE TITLE
[Question] Parameters

### ISSUE THREAD

**Issue by cgarciae** [google/flax#7]
Hi, I am curious how Flax deals with parameters given you see code like this

```python
def apply(self, x):
   x = Conv(x, ...)
```

where a new instance of the module `Conv` is created every time during apply. Even more curious about how parameter sharing will be approached. I think it will be important to explain this because all pytorch/tf.keras users would expect these layer to be instantiated during `__init__` and use in `apply`.

**Comment by avital** [comment]
Hi Cristian, we are in the process of clarifying this with better documentation.

(In general, the parameter model is quite similar to how it was in tf-slim, but without any global namespaces, no scopes other than the module hierarchy, and a more explicit parameter sharing API)

Compared to tf.keras/PyTorch this allows a few nice benefits such as shape inference, and interleaving any conditionals automatically into both parameter construction and application. In many cases this can reduce human error. But ultimately people may have different preferences.

I'll keep this open and close it once we have better documentation.

**Comment by avital** [comment]
Hi @cgarciae, we have the first version of an intro guide to Flax, which covers this. Can you take a look and let me know if this helps? https://flax.readthedocs.io/en/latest/notebooks/flax_intro.html#Flax-Modules 

And since we're already used to our API, your fresh eyes are very important! So, please, let us know what parts of the guide are confusing! And if you're so inclined, we welcome pull requests as well.

**Comment by marcvanzee** [comment]
Closing this since it has been 21 days since the last activity. Cristian, please feel free to open a new issue if you think your questions hasn't been answered properly yet.
