### ISSUE TITLE
Add best practices page for using JAX transformations like `jit`, `pmap`, `vmap`

### ISSUE THREAD

**Issue by avital** [google/flax#742]
Originally discussed in https://github.com/google/jax/discussions/5199

**Comment by marcvanzee** [comment]
Closing this issue since we haven't acted on it in 1.5 year. I think our Github Discussions provide a lot of insight already, as well as our examples. We should continue to add things there, and if we have time we can add more documentation in terms of HOWTOs (but it seems we do not have this time).
